### ISSUE TITLE
<h1>Critical error while processing request: /FF:FF:FF:FF:FF:FF</h1>

### ISSUE THREAD

**Issue by boredazfcuk** [rix1337/WakeOnLAN-API#2]
When post a MAC address to the container, I get this error:

> <h1>Critical error while processing request: /FF:FF:FF:FF:FF:FF</h1>

However, it does successfully wake the server, so I'm not sure why I'm seeing it.

**Comment by rix1337** [comment]
Good Issue, fix will be there any minute

**Comment by boredazfcuk** [comment]
Just upgraded. All good, thanks.
